const BACKEND='https://script.google.com/macros/s/AKfycbxUPLh0vcc6bLqsBNsCI8KqrvUhOSllC1ros6hJbLFrgvE5UBZtQA-pKAI12y51qVH1/exec';
const MAX_QR=2048,CAMERA={facingMode:'environment'},$=id=>document.getElementById(id);let scanner=null;
export function validateQr(value){const text=String(value||'').trim();if(!text)throw new Error('QR inválido: conteúdo vazio.');if(text.length>MAX_QR)throw new Error('QR inválido: conteúdo excessivo.');let url;try{url=new URL(text)}catch{throw new Error('QR inválido: use o link completo da NFC-e.')}if(url.protocol!=='https:'||url.hostname.toLowerCase()!=='sistemas.sefaz.am.gov.br'||url.pathname!=='/nfceweb/consultarNFCe.jsp')throw new Error('QR inválido: endereço fiscal não reconhecido.');return url.href}
export function backendUrl(value){return `${BACKEND}?qr=${encodeURIComponent(validateQr(value))}`}
function message(text,error=false){$('message').hidden=false;$('message').className=`card ${error?'error':'ok'}`;$('message').textContent=text}
function cameraError(error){const text=`${error?.name||''} ${error?.message||error||''}`.toLowerCase();if(/notallowed|permission|permiss/.test(text))return'Permissão de câmera negada. Libere a câmera nos ajustes do navegador e tente novamente.';if(/notfound|overconstrained|device/.test(text))return'Câmera indisponível neste dispositivo.';return'Não foi possível abrir a câmera. Tente novamente ou use Colar link.'}
export function redirectQr(value){location.assign(backendUrl(value))}
async function stop(){if(scanner){scanner.stop();scanner.destroy();scanner=null}const stream=$('video').srcObject;if(stream)stream.getTracks().forEach(track=>track.stop());$('video').srcObject=null;$('camera').hidden=true}
async function start(){await stop();$('camera').hidden=false;message('Abrindo câmera…');try{const {default:QrScanner}=await import('https://cdn.jsdelivr.net/npm/qr-scanner@1.4.2/qr-scanner.min.js');scanner=new QrScanner($('video'),result=>{stop();try{redirectQr(result.data||result)}catch(error){message(error.message,true)}},{preferredCamera:CAMERA.facingMode,returnDetailedScanResult:true,onDecodeError:error=>{if(error!==QrScanner.NO_QR_CODE_FOUND)message('QR não detectado. Aponte novamente ou use Colar link.',true)}});await scanner.start();message('Câmera ativa. Aponte para o QR da NFC-e.')}catch(error){await stop();message(cameraError(error),true)}}
if(typeof document!=='undefined'){$('scan').onclick=start;$('cancel').onclick=()=>{stop();message('Leitura cancelada. Você pode tentar novamente.')};$('paste').onclick=()=>{$('manual').hidden=!$('manual').hidden};$('send').onclick=()=>{try{redirectQr($('content').value)}catch(error){message(error.message,true)}}}
