const BACKEND='https://script.google.com/macros/s/AKfycbxUPLh0vcc6bLqsBNsCI8KqrvUhOSllC1ros6hJbLFrgvE5UBZtQA-pKAI12y51qVH1/exec';
const MAX_QR=2048,CAMERA={facingMode:'environment',width:{ideal:1920},height:{ideal:1080}},$=id=>document.getElementById(id);let scanner=null,redirecting=false,lastRejected='';
export function validateQr(value){const text=String(value||'').trim();if(!text)throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: conteúdo vazio.');if(text.length>MAX_QR)throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: conteúdo excessivo.');let url;try{url=new URL(text)}catch{throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: não é uma URL HTTPS.')}if(url.protocol!=='https:')throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: esquema não permitido.');return url.href}
export function backendUrl(value){return `${BACKEND}?qr=${encodeURIComponent(validateQr(value))}`}
export function qrDiagnostic(value){const raw=String(value??''),d={conteudoBruto:raw,comprimento:raw.length,protocolo:'',hostname:'',pathname:'',parametros:{}};try{const u=new URL(raw.trim());d.protocolo=u.protocol;d.hostname=u.hostname;d.pathname=u.pathname;for(const [key,val] of u.searchParams){if(Object.keys(d.parametros).length>=8)break;d.parametros[key]=val.slice(0,300)}}catch{}return d}
export function buildOptionalConstraints(capabilities={}){const constraints={};if(capabilities.width)constraints.width={ideal:Math.min(1920,capabilities.width.max||1920)};if(capabilities.height)constraints.height={ideal:Math.min(1080,capabilities.height.max||1080)};const focus=Array.isArray(capabilities.focusMode)?capabilities.focusMode:[];if(focus.includes('continuous'))constraints.advanced=[{focusMode:'continuous'}];return constraints}
export function fullScanRegion(video){const width=video.videoWidth||1024,height=video.videoHeight||768,downWidth=Math.min(1024,width),downHeight=Math.max(1,Math.round(height*downWidth/width));return{x:0,y:0,width,height,downScaledWidth:downWidth,downScaledHeight:downHeight}}
function message(text,error=false){$('message').hidden=false;$('message').className=`card ${error?'error':'ok'}`;$('message').textContent=text}
function cameraError(error){const text=`${error?.name||''} ${error?.message||error||''}`.toLowerCase();if(/notallowed|permission|permiss/.test(text))return'ERRO DE CÂMERA: permissão negada. Libere a câmera nos ajustes e tente novamente.';if(/notfound|overconstrained|device/.test(text))return'ERRO DE CÂMERA: câmera indisponível neste dispositivo.';return'ERRO DE CÂMERA: não foi possível abrir a câmera. Tente novamente ou use Colar link.'}
function showRejected(value,error){lastRejected=String(value??'');$('qrDiag').hidden=false;$('qrDiagText').textContent=JSON.stringify(qrDiagnostic(lastRejected),null,2);message(error.message,true)}
export function redirectQr(value){location.assign(backendUrl(value))}
async function stop(){if(scanner){scanner.stop();scanner.destroy();scanner=null}const stream=$('video').srcObject;if(stream)stream.getTracks().forEach(track=>track.stop());$('video').srcObject=null;$('camera').hidden=true}
async function tuneCamera(){const track=$('video').srcObject?.getVideoTracks?.()[0];if(!track)return{};const capabilities=track.getCapabilities?track.getCapabilities():{},before=track.getSettings?track.getSettings():{},constraints=buildOptionalConstraints(capabilities);if(track.applyConstraints&&Object.keys(constraints).length)try{await track.applyConstraints(constraints)}catch(error){message(`Câmera ativa; ajuste opcional não suportado (${error?.name||'erro'}).`)}const settings=track.getSettings?track.getSettings():before,diagnostic={settings,capabilities:{width:capabilities.width||null,height:capabilities.height||null,facingMode:capabilities.facingMode||null,focusMode:capabilities.focusMode||null,zoom:capabilities.zoom||null},aplicado:{resolucao:Boolean(constraints.width||constraints.height),focusContinuo:Boolean(constraints.advanced),zoom:false}};$('cameraDiag').textContent=JSON.stringify(diagnostic,null,2);return diagnostic}
async function decoded(value){if(redirecting)return;try{const target=backendUrl(value);redirecting=true;message('QR DECODIFICADO — URL FISCAL ENVIADA AO BACKEND');await stop();location.assign(target)}catch(error){showRejected(value,error)}}
async function start(){await stop();redirecting=false;$('camera').hidden=false;$('qrDiag').hidden=true;message('Abrindo câmera…');try{const {default:QrScanner}=await import('https://cdn.jsdelivr.net/npm/qr-scanner@1.4.2/qr-scanner.min.js');scanner=new QrScanner($('video'),result=>decoded(result.data||result),{preferredCamera:CAMERA.facingMode,calculateScanRegion:fullScanRegion,maxScansPerSecond:25,returnDetailedScanResult:true,onDecodeError:error=>{if(error!==QrScanner.NO_QR_CODE_FOUND)message(`ERRO DO DECODER: ${error?.message||error}`,true)}});await scanner.start();await tuneCamera();message('Câmera ativa. Mantenha o QR inteiro dentro do quadro e aproxime ou afaste até ficar nítido.')}catch(error){await stop();message(cameraError(error),true)}}
async function copyRejected(){if(!lastRejected)return;try{await navigator.clipboard.writeText(lastRejected);message('Conteúdo QR copiado.')}catch{message('Não foi possível copiar automaticamente. Selecione o conteúdo exibido.',true)}}
if(typeof document!=='undefined'){$('scan').onclick=start;$('cancel').onclick=()=>{stop();message('Leitura cancelada. Você pode tentar novamente.')};$('paste').onclick=()=>{$('manual').hidden=!$('manual').hidden};$('send').onclick=()=>decoded($('content').value);$('copyQr').onclick=copyRejected}
