const BACKEND='https://script.google.com/macros/s/AKfycbxUPLh0vcc6bLqsBNsCI8KqrvUhOSllC1ros6hJbLFrgvE5UBZtQA-pKAI12y51qVH1/exec';
const MAX_QR=2048,FALLBACK_DELAY=2500,FALLBACK_INTERVAL=350,CAMERA={facingMode:'environment',width:{ideal:1920},height:{ideal:1080}},$=id=>document.getElementById(id);let scanner=null,redirecting=false,lastRejected='',lastDecoded=null,fallbackTimer=null,fallbackLoopTimer=null,zxingReader=null,zxingPromise=null,cameraInfo={},metrics=null,diagnosticMode=false,diagnosticStarted=0,readings=[],lastReadingAt={},zxingBusy=false;
export function validateQr(value){const text=String(value||'').trim();if(!text)throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: conteúdo vazio.');if(text.length>MAX_QR)throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: conteúdo excessivo.');let url;try{url=new URL(text)}catch{throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: URL malformada.')}const fiscalAm=url.hostname.toLowerCase()==='sistemas.sefaz.am.gov.br'&&url.pathname==='/nfceweb/consultarNFCe.jsp';if(url.protocol!=='https:'&&!(url.protocol==='http:'&&fiscalAm))throw new Error('QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: esquema ou origem não permitidos.');return text}
export function backendUrl(value){return `${BACKEND}?qr=${encodeURIComponent(validateQr(value))}`}
export function diagnosticUrl(value){const raw=String(value??''),parteUrl=raw.split('|')[0],d={parteUrl,protocol:'',hostname:'',pathname:'',search:''};try{const u=new URL(parteUrl);d.protocol=u.protocol;d.hostname=u.hostname;d.pathname=u.pathname;d.search=u.search}catch{}return d}
export function qrDiagnostic(value){const raw=String(value??''),parsed=diagnosticUrl(raw),d={conteudoBruto:raw,comprimento:raw.length,protocolo:parsed.protocol,hostname:parsed.hostname,pathname:parsed.pathname,parametros:{}};try{const u=new URL(parsed.parteUrl);for(const [key,val] of u.searchParams){if(Object.keys(d.parametros).length>=8)break;d.parametros[key]=val.slice(0,300)}}catch{}return d}
export function decodedDiagnostic(value,decoder,startTime,decodedAt){const raw=String(value??''),parsed=diagnosticUrl(raw),d={decoderQueDecodificou:decoder,tempoAteDecodificacaoMs:Math.max(0,Math.round(decodedAt-startTime)),conteudoBruto:raw,comprimento:raw.length,primeirosCaracteres:raw.slice(0,160),ultimosCaracteres:raw.slice(-160),scheme:parsed.protocol,hostname:parsed.hostname,pathname:parsed.pathname,search:parsed.search};return d}
export function studyReading(value,decoder,attempt,startTime,decodedAt,timestamp=new Date().toISOString()){const raw=String(value??''),parsed=diagnosticUrl(raw);let segment=(parsed.parteUrl.match(/\d+$/)||[''])[0];try{segment=new URL(parsed.parteUrl).searchParams.get('p')||segment}catch{}return{tentativa:attempt,decoder,conteudoBruto:raw,comprimentoTotal:raw.length,quantidadeDigitosAntesPipe:(segment.match(/\d/g)||[]).length,protocol:parsed.protocol,hostname:parsed.hostname,pathname:parsed.pathname,search:parsed.search,timestamp,tempoDecodificacaoMs:Math.max(0,Math.round(decodedAt-startTime))}}
export function studyConsensus(items){const variants=[...new Set(items.map(x=>x.conteudoBruto))],values=name=>items.filter(x=>x.decoder===name).map(x=>x.conteudoBruto),sets=name=>[...new Set(values(name))].sort(),primary=sets('qr-scanner'),fallback=sets('ZXing'),same=primary.length&&fallback.length?JSON.stringify(primary)===JSON.stringify(fallback)?'SIM':'NÃO':'INDETERMINADO';return{leituras:items.length,todasLeiturasIdenticas:items.length>1&&variants.length===1?'SIM':items.length>1?'NÃO':'INDETERMINADO',qrScannerIgualZXing:same,quantidadeVariantes:variants.length,leiturasQrScanner:values('qr-scanner').length,leiturasZXing:values('ZXing').length,leiturasCapturaManual:values('captura-manual-ZXing').length}}
export function buildOptionalConstraints(capabilities={}){const constraints={};if(capabilities.width)constraints.width={ideal:Math.min(1920,capabilities.width.max||1920)};if(capabilities.height)constraints.height={ideal:Math.min(1080,capabilities.height.max||1080)};const focus=Array.isArray(capabilities.focusMode)?capabilities.focusMode:[];if(focus.includes('continuous'))constraints.advanced=[{focusMode:'continuous'}];return constraints}
export function fullScanRegion(video){const width=video.videoWidth||1280,height=video.videoHeight||720,downWidth=Math.min(1280,width),downHeight=Math.max(1,Math.round(height*downWidth/width));return{x:0,y:0,width,height,downScaledWidth:downWidth,downScaledHeight:downHeight}}
export function frameSize(width,height,maxWidth){const sourceWidth=width||1280,sourceHeight=height||720,w=Math.min(maxWidth,sourceWidth),h=Math.max(1,Math.round(sourceHeight*w/sourceWidth));return{width:w,height:h}}
export function newMetrics(now=0){return{inicio:now,primeiraTentativaMs:null,framesPrimario:0,framesFallback:0,decoderAtivo:'qr-scanner',fallbackAcionado:false,timeoutFallbackMs:FALLBACK_DELAY,resultado:'A — QR NÃO DETECTADO'}}
export function recordAttempt(state,decoder,now){if(state.primeiraTentativaMs===null)state.primeiraTentativaMs=Math.max(0,Math.round(now-state.inicio));if(decoder==='ZXing')state.framesFallback+=1;else state.framesPrimario+=1;const elapsed=Math.max(1,now-state.inicio);state.fpsEfetivo=Number(((state.framesPrimario+state.framesFallback)*1000/elapsed).toFixed(1));return state}
function message(text,error=false){$('message').hidden=false;$('message').className=`card ${error?'error':'ok'}`;$('message').textContent=text}
function cameraError(error){const text=`${error?.name||''} ${error?.message||error||''}`.toLowerCase();if(/notallowed|permission|permiss/.test(text))return'ERRO DE CÂMERA: permissão negada. Libere a câmera nos ajustes e tente novamente.';if(/notfound|overconstrained|device/.test(text))return'ERRO DE CÂMERA: câmera indisponível neste dispositivo.';return'ERRO DE CÂMERA: não foi possível abrir a câmera. Tente novamente ou use Colar link.'}
function showRejected(value,error){lastRejected=String(value??'');const rejection={motivoRejeicao:error.message,...(lastDecoded||decodedDiagnostic(lastRejected,'desconhecido',now(),now()))};$('qrDiag').hidden=false;$('qrDiagText').textContent=JSON.stringify(rejection,null,2);message(`QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO: ${error.message}`,true)}
export function redirectQr(value){location.assign(backendUrl(value))}
function now(){return typeof performance!=='undefined'?performance.now():Date.now()}
function renderStudy(){const data={consenso:studyConsensus(readings),leituras:readings};$('studyText').textContent=JSON.stringify(data,null,2);$('studyCount').textContent=`${readings.length} leitura(s). Objetivo: 3 qr-scanner + 1 ZXing + 1 captura manual.`}
function recordStudy(value,decoder){const at=now();if(decoder!=='captura-manual-ZXing'&&at-(lastReadingAt[decoder]||0)<600)return;lastReadingAt[decoder]=at;if(readings.length>=20)return;readings.push(studyReading(value,decoder,readings.length+1,diagnosticStarted,at));renderStudy();message(`Leitura diagnóstica ${readings.length} registrada por ${decoder}. Nenhum redirecionamento foi realizado.`)}
function updateDiagnostic(){if(!$('cameraDiag')||!metrics)return;const video=$('video'),primary=fullScanRegion(video),fallback=frameSize(video.videoWidth||1920,video.videoHeight||1080,1920);$('cameraDiag').textContent=JSON.stringify({...cameraInfo,decodificacao:{...metrics,resolucaoVideo:`${video.videoWidth||0}x${video.videoHeight||0}`,framePrimario:`${primary.downScaledWidth}x${primary.downScaledHeight}`,frameFallback:`${fallback.width}x${fallback.height}`,decoderPrimario:'qr-scanner 1.4.2',decoderFallback:'ZXing Browser 0.2.1',deteccaoSemDecodificacao:'não exposta pelos decoders; frames/tentativas são a métrica equivalente'}},null,2)}
function attempted(decoder){if(metrics)recordAttempt(metrics,decoder,now());updateDiagnostic()}
function clearFallback(){clearTimeout(fallbackTimer);clearTimeout(fallbackLoopTimer);fallbackTimer=null;fallbackLoopTimer=null}
async function stop(){clearFallback();if(scanner){scanner.stop();scanner.destroy();scanner=null}const stream=$('video').srcObject;if(stream)stream.getTracks().forEach(track=>track.stop());$('video').srcObject=null;$('camera').hidden=true}
async function tuneCamera(){const track=$('video').srcObject?.getVideoTracks?.()[0];if(!track)return{};const capabilities=track.getCapabilities?track.getCapabilities():{},before=track.getSettings?track.getSettings():{},constraints=buildOptionalConstraints(capabilities);if(track.applyConstraints&&Object.keys(constraints).length)try{await track.applyConstraints(constraints)}catch(error){message(`Câmera ativa; ajuste opcional não suportado (${error?.name||'erro'}).`)}const settings=track.getSettings?track.getSettings():before;cameraInfo={settings,capabilities:{width:capabilities.width||null,height:capabilities.height||null,facingMode:capabilities.facingMode||null,focusMode:capabilities.focusMode||null,zoom:capabilities.zoom||null},aplicado:{resolucao:Boolean(constraints.width||constraints.height),focusContinuo:Boolean(constraints.advanced),zoom:false}};updateDiagnostic();return cameraInfo}
function loadZxing(){if(zxingPromise)return zxingPromise;zxingPromise=new Promise((resolve,reject)=>{if(globalThis.ZXingBrowser)return resolve(globalThis.ZXingBrowser);const script=document.createElement('script');script.src='./vendor/zxing-browser-0.2.1.min.js';script.onload=()=>resolve(globalThis.ZXingBrowser);script.onerror=()=>reject(new Error('bundle ZXing indisponível'));document.head.appendChild(script)});return zxingPromise}
function canvasFrame(maxWidth){const video=$('video'),size=frameSize(video.videoWidth,video.videoHeight,maxWidth),canvas=$('frame');canvas.width=size.width;canvas.height=size.height;canvas.getContext('2d',{willReadFrequently:true}).drawImage(video,0,0,size.width,size.height);return canvas}
async function decodeFallback(maxWidth=1920){const ZXing=await loadZxing();zxingReader ||= new ZXing.BrowserQRCodeReader();attempted('ZXing');const result=zxingReader.decodeFromCanvas(canvasFrame(maxWidth));return result.getText?result.getText():String(result)}
async function fallbackTick(){if(redirecting||!scanner)return;if(!zxingBusy){zxingBusy=true;try{const value=await decodeFallback();await decoded(value,'ZXing')}catch{}finally{zxingBusy=false}}if(!redirecting&&scanner)fallbackLoopTimer=setTimeout(fallbackTick,FALLBACK_INTERVAL)}
async function activateFallback(){if(redirecting||!scanner)return;metrics.fallbackAcionado=true;metrics.decoderAtivo='qr-scanner + ZXing fallback';metrics.resultado='A — QR NÃO DETECTADO; fallback acionado';updateDiagnostic();$('capture').hidden=false;message("QR ainda não identificado. Mantenha-o inteiro no quadro ou tente 'Capturar imagem'.");await fallbackTick()}
function manualMessage(text,error=false){$('manualStatus').hidden=false;$('manualStatus').className=error?'error':'';$('manualStatus').textContent=text}
function noQrError(error){return /notfound|not found|no qr|no multiformat/i.test(`${error?.name||''} ${error?.message||error||''}`)}
async function captureImage(){if(redirecting||!scanner||zxingBusy)return;const button=$('capture'),size=frameSize($('video').videoWidth,$('video').videoHeight,2560);zxingBusy=true;button.disabled=true;metrics.capturaManualExecutada=true;metrics.resolucaoCaptura=`${size.width}x${size.height}`;metrics.resultadoCaptura='PROCESSANDO';metrics.decoderCaptura='captura-manual-ZXing';updateDiagnostic();manualMessage('Imagem capturada. Tentando decodificar...');message('Imagem capturada. Tentando decodificar...');await new Promise(resolve=>requestAnimationFrame(resolve));try{const value=await decodeFallback(2560);metrics.resultadoCaptura='QR decodificado pela captura manual';updateDiagnostic();manualMessage('QR decodificado pela captura manual');await decoded(value,'captura-manual-ZXing')}catch(error){if(noQrError(error)){metrics.resultadoCaptura='Nenhum QR identificado na imagem capturada';manualMessage('Nenhum QR identificado na imagem capturada',true)}else{metrics.resultadoCaptura=`Erro ao processar imagem capturada: ${error?.message||error}`;manualMessage(metrics.resultadoCaptura,true)}metrics.resultado='B — imagem capturada, mas não decodificada';updateDiagnostic();message(metrics.resultadoCaptura,true)}finally{zxingBusy=false;if(scanner&&!redirecting)button.disabled=false}}
async function decoded(value,decoder='qr-scanner'){if(redirecting)return;const raw=String(value??'');if(diagnosticMode){recordStudy(raw,decoder);return}lastDecoded=decodedDiagnostic(raw,decoder,metrics?.inicio??now(),now());if(metrics){Object.assign(metrics,lastDecoded);metrics.resultado='C — QR DECODIFICADO';metrics.decoderAtivo=decoder;updateDiagnostic()}try{const target=backendUrl(raw);redirecting=true;message(`QR DECODIFICADO — URL FISCAL ENVIADA AO BACKEND (${decoder})`);await stop();location.assign(target)}catch(error){if(metrics){metrics.resultado='QR DECODIFICADO — CONTEÚDO NÃO SUPORTADO';metrics.motivoRejeicao=error.message;updateDiagnostic()}showRejected(raw,error)}}
async function start(){await stop();redirecting=false;lastDecoded=null;metrics=newMetrics(now());metrics.capturaManualExecutada=false;metrics.resolucaoCaptura='';metrics.resultadoCaptura='NÃO EXECUTADA';metrics.decoderCaptura='captura-manual-ZXing';cameraInfo={};$('camera').hidden=false;$('capture').hidden=true;$('forceZxing').hidden=true;$('capture').disabled=false;$('manualStatus').hidden=true;$('qrDiag').hidden=true;message('Abrindo câmera…');try{const {default:QrScanner}=await import('https://cdn.jsdelivr.net/npm/qr-scanner@1.4.2/qr-scanner.min.js');scanner=new QrScanner($('video'),result=>{attempted('qr-scanner');decoded(result.data||result,'qr-scanner')},{preferredCamera:CAMERA.facingMode,calculateScanRegion:fullScanRegion,maxScansPerSecond:25,returnDetailedScanResult:true,onDecodeError:error=>{attempted('qr-scanner');if(error!==QrScanner.NO_QR_CODE_FOUND)message(`ERRO DO DECODER: ${error?.message||error}`,true)}});await scanner.start();await tuneCamera();message('Câmera ativa. Mantenha o QR inteiro dentro do quadro e aproxime ou afaste até ficar nítido.');fallbackTimer=setTimeout(activateFallback,FALLBACK_DELAY)}catch(error){await stop();message(cameraError(error),true)}}
async function startStudy(){diagnosticMode=true;diagnosticStarted=now();readings=[];lastReadingAt={};$('study').hidden=false;$('forceZxing').hidden=false;renderStudy();await start();$('capture').hidden=false;$('forceZxing').hidden=false;message('Modo diagnóstico ativo: as leituras não serão enviadas ao backend.')}
async function forceZxing(){if(!scanner||zxingBusy)return;zxingBusy=true;$('forceZxing').disabled=true;message('Tentando leitura forçada com ZXing…');try{await decoded(await decodeFallback(),'ZXing')}catch(error){message(`ZXing não decodificou este frame: ${error?.message||error}`,true)}finally{zxingBusy=false;$('forceZxing').disabled=false}}
async function copyStudy(){const data=JSON.stringify({consenso:studyConsensus(readings),leituras:readings},null,2);try{await navigator.clipboard.writeText(data);message('Diagnóstico copiado.')}catch{message('Não foi possível copiar o diagnóstico automaticamente.',true)}}
async function copyRejected(){if(!lastRejected)return;try{await navigator.clipboard.writeText(lastRejected);message('Conteúdo QR copiado.')}catch{message('Não foi possível copiar automaticamente. Selecione o conteúdo exibido.',true)}}
if(typeof document!=='undefined'){$('scan').onclick=()=>{diagnosticMode=false;$('study').hidden=true;start()};$('diagnose').onclick=startStudy;$('forceZxing').onclick=forceZxing;$('copyStudy').onclick=copyStudy;$('cancel').onclick=()=>{stop();message('Leitura cancelada. Você pode tentar novamente.')};$('capture').onclick=captureImage;$('paste').onclick=()=>{$('manual').hidden=!$('manual').hidden};$('send').onclick=()=>decoded($('content').value,'link colado');$('copyQr').onclick=copyRejected}
