import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {backendUrl,buildOptionalConstraints,fullScanRegion,qrDiagnostic,validateQr} from './app.js';
const key='12345678901234567890123456789012345678901234',valid=`https://sistemas.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp?p=${key}|2|1|1`;
test('aceita NFC-e SEFAZ-AM HTTPS e preserva encoding',()=>{assert.equal(validateQr(valid),valid);assert.equal(new URL(backendUrl(valid)).searchParams.get('qr'),valid)});
test('outra HTTPS plausível é enviada ao backend',()=>{const value='https://consulta.exemplo.gov.br/nova/rota?chave=123';assert.equal(validateQr(value),value);assert.equal(new URL(backendUrl(value)).searchParams.get('qr'),value)});
test('rejeita vazio e esquemas inseguros',()=>{for(const value of ['',`javascript:${valid}`,`data:text/plain,${valid}`,`file://${valid}`])assert.throws(()=>validateQr(value),/CONTEÚDO NÃO SUPORTADO/)});
test('rejeita conteúdo excessivo',()=>assert.throws(()=>validateQr(`https://example.com/?p=${'1'.repeat(2100)}`),/excessivo/));
test('diagnóstico descreve bruto, tamanho e URL sem armazenar',()=>{const d=qrDiagnostic('https://example.com/a?p=1');assert.equal(d.conteudoBruto,'https://example.com/a?p=1');assert.equal(d.comprimento,25);assert.equal(d.protocolo,'https:');assert.equal(d.hostname,'example.com');assert.equal(d.pathname,'/a');assert.equal(d.parametros.p,'1')});
test('constraints são opcionais em navegador sem capabilities',()=>assert.deepEqual(buildOptionalConstraints({}),{}));
test('constraints usam resolução e foco somente quando suportados',()=>assert.deepEqual(buildOptionalConstraints({width:{max:1280},height:{max:720},focusMode:['manual','continuous']}),{width:{ideal:1280},height:{ideal:720},advanced:[{focusMode:'continuous'}]}));
test('decoder analisa frame inteiro em resolução suficiente',()=>assert.deepEqual(fullScanRegion({videoWidth:1920,videoHeight:1080}),{x:0,y:0,width:1920,height:1080,downScaledWidth:1024,downScaledHeight:576}));
test('frontend mostra e copia bruto somente no painel de erro',()=>{const html=readFileSync(new URL('./index.html',import.meta.url),'utf8'),source=readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.match(html,/id="qrDiag"[^>]*hidden/);assert.match(html,/Copiar conteúdo QR/);assert.match(source,/navigator\.clipboard\.writeText\(lastRejected\)/);assert.doesNotMatch(source,/localStorage|sessionStorage|fetch\s*\(/i)});
test('leitura válida bloqueia repetição, para câmera e redireciona',()=>{const source=readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.match(source,/if\(redirecting\)return/);assert.match(source,/redirecting=true;message\('QR DECODIFICADO/);assert.match(source,/await stop\(\);location\.assign\(target\)/)});
test('leitura rejeitada mantém scanner ativo para frame posterior',()=>{const source=readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.match(source,/catch\(error\)\{showRejected\(value,error\)\}/);assert.doesNotMatch(source,/catch\(error\)\{await stop\(\);showRejected/)});
test('frontend não contém segredos, persistência ou escrita pública',()=>{const source=readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.doesNotMatch(source,/password|client_secret|bearer/i);assert.match(source,/facingMode:'environment'/);assert.match(source,/qr-scanner@1\.4\.2/)});
test('manifest prepara instalação standalone',()=>{const manifest=JSON.parse(readFileSync(new URL('./manifest.webmanifest',import.meta.url),'utf8'));assert.equal(manifest.display,'standalone');assert.ok(manifest.icons.length)});
